Improve static content handling (#5553)
* Add failing tests

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix tests (KTOR-9526), improve static content performance slightly

Improves the performance of static content slightly, by using arrays instead of lists.

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Clean up PreCompressed.kt, fix minor issues

Fixes:
- Vary header was not added for static paths (KTOR-8326)

Additions:
- order best compression fit by file size
  - does not apply to resources
- Reject static file request sooner if file does not exist.
  Previously only rejected if no other compressed file
  could be found, however it's better to reject sooner.

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Add support for zstd & deflate compressed static files (KTOR-8672)

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix failing tests

The old behaviour was unintuitive anyways

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* go away stupid chatbot

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Update tests to use junit temp directories

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Cleanup tests

Changes:
- Merges a couple of existing tests
- Ensures behaviour is tested for all static content types

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix formatting & update api dump

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Remove failing tests

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Add static content filtering

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Update api dump

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Remove SensitivityWatchEventModifier

It's was deprecated in JDK 21, and is now ignored. It will eventually be
 removed, and this will become a NoClassDefFoundError.
It already produces this error, and apparently has already been removed
 on some linux distros.

See:
- JDK-8303188
- JDK-8303175
- JDK-8303471
- JDK-8303413
- openjdk/jdk#12746 (PR which deprecates it for removal)
- openjdk/jdk@ae290541d17be77bbedf56a4592102ead4e4691e
- openjdk/jdk#12795 (PR which removes the functionality)
- KTOR-1647

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix static content filtering

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Add test to check size of Last-Modified header for static content

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Cache default file response for static file system

Adds caching for the default file system when using staticFileSystem()
The default file is cached in memory, and the files are watched so they
 can be refreshed if they are updated.

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Remove unnecessary parameters

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* add staticFileSystem() which takes a Path instead of String

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* add staticPaths()

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Avoid calling relativePath() twice

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Suppress deprecation for deprecated functions in StaticContent.kt

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Update api dump

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Eliminate intermediary Accept-Encoding Set

because Accept-Encoding is almost always a very small set, just
iterating over it is likely faster compared to a set lookup.
This also avoids unecessary intermediary allocations.

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix RFC 9110 compliance for content encoding matching

- Matches content encodings case-insensitively
- Do not match content encodings with q=0

Currently, it does not return a 415 when the identity encoding has q=0
to mirror the behaviour of Compression plugin.

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Try to minimize allocations

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Add support for cached files to staticFiles()

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

* Fix bug in relativePath()

oopsies

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>

---------

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>