Remove SensitivityWatchEventModifier
It's was deprecated in JDK 21, and is now ignored. It will eventually be
 removed, and this will become a NoClassDefFoundError.
It already produces this error, and apparently has already been removed
 on some linux distros.

See:
- JDK-8303188
- JDK-8303175
- JDK-8303471
- JDK-8303413
- openjdk/jdk#12746 (PR which deprecates it for removal)
- openjdk/jdk@ae290541d17be77bbedf56a4592102ead4e4691e
- openjdk/jdk#12795 (PR which removes the functionality)
- KTOR-1647

Signed-off-by: solonovamax <solonovamax@12oclockpoint.com>